services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    env_file:
      - ./client/.env.production
    environment:
      - PORT=${CLIENT_PORT}
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - ./server/.env.production
    environment:
      - GO_ENV=production
      - DOCKER_ENV=true