services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - ./server/.env
      - ./server/.env.production
    environment:
      - GO_ENV=production
      - DOCKER_ENV=true