# 빌드 단계
FROM golang:1.23-alpine AS builder

# 복사 될 디렉토리
WORKDIR /app

# 모듈 의존성 복사
COPY go.mod go.sum ./
RUN go mod download

# 소스 코드 복사
COPY . .

# 애플리케이션 빌드
RUN CGO_ENABLED=0 GOOS=linux go build -o main cmd/main.go

# 실행 단계
FROM alpine:latest

WORKDIR /app

# 빌드 단계에서 생성된 바이너리만 복사
COPY --from=builder /app/main .

# 애플리케이션 실행
CMD ["./main"]