/**
 * 엔드포인트
 * @constant
 * @type {Object}
 * @property {string} API - API 엔드포인트
 */
export default {
  API: process.env.NEXT_PUBLIC_API_ENDPOINT as string,
  POWER_BALL: process.env.NEXT_PUBLIC_POWER_BALL_API_ENDPOINT as string,
  POWER_BALL_GENERATE: process.env.NEXT_PUBLIC_POWER_BALL_GENERATE_ENDPOINT as string,
  POWER_BALL_STATISTICS: process.env.NEXT_PUBLIC_POWER_BALL_STATISTICS_ENDPOINT as string,
  POWER_BALL_DRAWS: process.env.NEXT_PUBLIC_POWER_BALL_DRAWS_ENDPOINT as string,
  POWER_BALL_DRAW_DETAIL: process.env.NEXT_PUBLIC_POWER_BALL_DRAW_DETAIL_ENDPOINT as string,
  POWER_BALL_NUMBER_FREQUENCY: process.env
    .NEXT_PUBLIC_POWER_BALL_NUMBER_FREQUENCY_ENDPOINT as string,
  MEGA_MILLIONS: process.env.NEXT_PUBLIC_MEGA_MILLIONS_API_ENDPOINT as string,
  MEGA_MILLIONS_GENERATE: process.env.NEXT_PUBLIC_MEGA_MILLIONS_GENERATE_ENDPOINT as string,
  MEGA_MILLIONS_STATISTICS: process.env.NEXT_PUBLIC_MEGA_MILLIONS_STATISTICS_ENDPOINT as string,
  MEGA_MILLIONS_DRAWS: process.env.NEXT_PUBLIC_MEGA_MILLIONS_DRAWS_ENDPOINT as string,
  MEGA_MILLIONS_DRAW_DETAIL: process.env.NEXT_PUBLIC_MEGA_MILLIONS_DRAW_DETAIL_ENDPOINT as string,
  MEGA_MILLIONS_NUMBER_FREQUENCY: process.env
    .NEXT_PUBLIC_MEGA_MILLIONS_NUMBER_FREQUENCY_ENDPOINT as string,
} as const;
